### PR TITLE
Proposing some additions

### PR DESCRIPTION
**Pull request by purcell**
Thanks for Spacchetti & Spago! :-)

### CODE REVIEW

**Comment by f-f** [comment]
Hi @purcell! Thanks for the PR 🙂 

We literally [just merged Spacchetti into the official package-set](https://github.com/purescript/package-sets/issues/270) and this repo is now considered deprecated in favor of [that repo](https://github.com/purescript/package-sets). I just didn't have the time to add a deprecation notice and archive this yet (which I'll do it later today)

There's a [release out](https://github.com/purescript/package-sets/releases/tag/psc-0.12.3-20190227), so you can start using it already with Spago.

So could you file this PR in there? (some deps are already there, e.g. `remote-data`)

**Comment by purcell** [comment]
Great, thanks - I've filed https://github.com/purescript/package-sets/pull/274 instead now.

**Comment by purcell** [comment]
Might actually be worth adding a README note now, directing people to `package-sets`, and then archiving this repo.

**Comment by f-f** [comment]
@purcell thank you!
Yeah I opened #74 to add a deprecation notice and instructions for users to switch, I'll archive the repo after we merge it

**Comment by purcell** [comment]
Awesome, thanks for your help!

**Comment by f-f** [comment]
You're welcome! 🙂

**Pull request closed without merging**
